name: text_the_answer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.2.4
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.1
  supabase_flutter: ^2.8.4
  iconsax_plus: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
       
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        
  assets:
    - assets/images/onboard1.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png
    - assets/images/splash_page.png
    - assets/images/man.png
    - assets/images/woman.png
    
    - .env